// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invoices.proto

package org.example.protos;

/**
 * Protobuf type {@code Invoices}
 */
public final class Invoices extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Invoices)
    InvoicesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Invoices.newBuilder() to construct.
  private Invoices(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Invoices() {
    invoices_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Invoices();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.protos.InvoicesProtos.internal_static_Invoices_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.protos.InvoicesProtos.internal_static_Invoices_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.protos.Invoices.class, org.example.protos.Invoices.Builder.class);
  }

  public static final int INVOICES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<org.example.protos.Invoice> invoices_;
  /**
   * <code>repeated .Invoice Invoices = 1;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.protos.Invoice> getInvoicesList() {
    return invoices_;
  }
  /**
   * <code>repeated .Invoice Invoices = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.protos.InvoiceOrBuilder> 
      getInvoicesOrBuilderList() {
    return invoices_;
  }
  /**
   * <code>repeated .Invoice Invoices = 1;</code>
   */
  @java.lang.Override
  public int getInvoicesCount() {
    return invoices_.size();
  }
  /**
   * <code>repeated .Invoice Invoices = 1;</code>
   */
  @java.lang.Override
  public org.example.protos.Invoice getInvoices(int index) {
    return invoices_.get(index);
  }
  /**
   * <code>repeated .Invoice Invoices = 1;</code>
   */
  @java.lang.Override
  public org.example.protos.InvoiceOrBuilder getInvoicesOrBuilder(
      int index) {
    return invoices_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < invoices_.size(); i++) {
      output.writeMessage(1, invoices_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < invoices_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, invoices_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.protos.Invoices)) {
      return super.equals(obj);
    }
    org.example.protos.Invoices other = (org.example.protos.Invoices) obj;

    if (!getInvoicesList()
        .equals(other.getInvoicesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getInvoicesCount() > 0) {
      hash = (37 * hash) + INVOICES_FIELD_NUMBER;
      hash = (53 * hash) + getInvoicesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.protos.Invoices parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protos.Invoices parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protos.Invoices parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protos.Invoices parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protos.Invoices parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protos.Invoices parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protos.Invoices parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protos.Invoices parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.protos.Invoices parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.protos.Invoices parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.protos.Invoices parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protos.Invoices parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.protos.Invoices prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Invoices}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Invoices)
      org.example.protos.InvoicesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.protos.InvoicesProtos.internal_static_Invoices_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.protos.InvoicesProtos.internal_static_Invoices_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.protos.Invoices.class, org.example.protos.Invoices.Builder.class);
    }

    // Construct using org.example.protos.Invoices.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (invoicesBuilder_ == null) {
        invoices_ = java.util.Collections.emptyList();
      } else {
        invoices_ = null;
        invoicesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.protos.InvoicesProtos.internal_static_Invoices_descriptor;
    }

    @java.lang.Override
    public org.example.protos.Invoices getDefaultInstanceForType() {
      return org.example.protos.Invoices.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.protos.Invoices build() {
      org.example.protos.Invoices result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.protos.Invoices buildPartial() {
      org.example.protos.Invoices result = new org.example.protos.Invoices(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.protos.Invoices result) {
      if (invoicesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          invoices_ = java.util.Collections.unmodifiableList(invoices_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.invoices_ = invoices_;
      } else {
        result.invoices_ = invoicesBuilder_.build();
      }
    }

    private void buildPartial0(org.example.protos.Invoices result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.protos.Invoices) {
        return mergeFrom((org.example.protos.Invoices)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.protos.Invoices other) {
      if (other == org.example.protos.Invoices.getDefaultInstance()) return this;
      if (invoicesBuilder_ == null) {
        if (!other.invoices_.isEmpty()) {
          if (invoices_.isEmpty()) {
            invoices_ = other.invoices_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInvoicesIsMutable();
            invoices_.addAll(other.invoices_);
          }
          onChanged();
        }
      } else {
        if (!other.invoices_.isEmpty()) {
          if (invoicesBuilder_.isEmpty()) {
            invoicesBuilder_.dispose();
            invoicesBuilder_ = null;
            invoices_ = other.invoices_;
            bitField0_ = (bitField0_ & ~0x00000001);
            invoicesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getInvoicesFieldBuilder() : null;
          } else {
            invoicesBuilder_.addAllMessages(other.invoices_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.example.protos.Invoice m =
                  input.readMessage(
                      org.example.protos.Invoice.PARSER,
                      extensionRegistry);
              if (invoicesBuilder_ == null) {
                ensureInvoicesIsMutable();
                invoices_.add(m);
              } else {
                invoicesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<org.example.protos.Invoice> invoices_ =
      java.util.Collections.emptyList();
    private void ensureInvoicesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        invoices_ = new java.util.ArrayList<org.example.protos.Invoice>(invoices_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.protos.Invoice, org.example.protos.Invoice.Builder, org.example.protos.InvoiceOrBuilder> invoicesBuilder_;

    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public java.util.List<org.example.protos.Invoice> getInvoicesList() {
      if (invoicesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(invoices_);
      } else {
        return invoicesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public int getInvoicesCount() {
      if (invoicesBuilder_ == null) {
        return invoices_.size();
      } else {
        return invoicesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public org.example.protos.Invoice getInvoices(int index) {
      if (invoicesBuilder_ == null) {
        return invoices_.get(index);
      } else {
        return invoicesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public Builder setInvoices(
        int index, org.example.protos.Invoice value) {
      if (invoicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicesIsMutable();
        invoices_.set(index, value);
        onChanged();
      } else {
        invoicesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public Builder setInvoices(
        int index, org.example.protos.Invoice.Builder builderForValue) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.set(index, builderForValue.build());
        onChanged();
      } else {
        invoicesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public Builder addInvoices(org.example.protos.Invoice value) {
      if (invoicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicesIsMutable();
        invoices_.add(value);
        onChanged();
      } else {
        invoicesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public Builder addInvoices(
        int index, org.example.protos.Invoice value) {
      if (invoicesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInvoicesIsMutable();
        invoices_.add(index, value);
        onChanged();
      } else {
        invoicesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public Builder addInvoices(
        org.example.protos.Invoice.Builder builderForValue) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.add(builderForValue.build());
        onChanged();
      } else {
        invoicesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public Builder addInvoices(
        int index, org.example.protos.Invoice.Builder builderForValue) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.add(index, builderForValue.build());
        onChanged();
      } else {
        invoicesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public Builder addAllInvoices(
        java.lang.Iterable<? extends org.example.protos.Invoice> values) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, invoices_);
        onChanged();
      } else {
        invoicesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public Builder clearInvoices() {
      if (invoicesBuilder_ == null) {
        invoices_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        invoicesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public Builder removeInvoices(int index) {
      if (invoicesBuilder_ == null) {
        ensureInvoicesIsMutable();
        invoices_.remove(index);
        onChanged();
      } else {
        invoicesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public org.example.protos.Invoice.Builder getInvoicesBuilder(
        int index) {
      return getInvoicesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public org.example.protos.InvoiceOrBuilder getInvoicesOrBuilder(
        int index) {
      if (invoicesBuilder_ == null) {
        return invoices_.get(index);  } else {
        return invoicesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public java.util.List<? extends org.example.protos.InvoiceOrBuilder> 
         getInvoicesOrBuilderList() {
      if (invoicesBuilder_ != null) {
        return invoicesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(invoices_);
      }
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public org.example.protos.Invoice.Builder addInvoicesBuilder() {
      return getInvoicesFieldBuilder().addBuilder(
          org.example.protos.Invoice.getDefaultInstance());
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public org.example.protos.Invoice.Builder addInvoicesBuilder(
        int index) {
      return getInvoicesFieldBuilder().addBuilder(
          index, org.example.protos.Invoice.getDefaultInstance());
    }
    /**
     * <code>repeated .Invoice Invoices = 1;</code>
     */
    public java.util.List<org.example.protos.Invoice.Builder> 
         getInvoicesBuilderList() {
      return getInvoicesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.protos.Invoice, org.example.protos.Invoice.Builder, org.example.protos.InvoiceOrBuilder> 
        getInvoicesFieldBuilder() {
      if (invoicesBuilder_ == null) {
        invoicesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.protos.Invoice, org.example.protos.Invoice.Builder, org.example.protos.InvoiceOrBuilder>(
                invoices_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        invoices_ = null;
      }
      return invoicesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Invoices)
  }

  // @@protoc_insertion_point(class_scope:Invoices)
  private static final org.example.protos.Invoices DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.protos.Invoices();
  }

  public static org.example.protos.Invoices getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Invoices>
      PARSER = new com.google.protobuf.AbstractParser<Invoices>() {
    @java.lang.Override
    public Invoices parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Invoices> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Invoices> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.protos.Invoices getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

