// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invoices.proto

package org.example.protos;

public interface InvoiceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Invoice)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string invoice_no = 1;</code>
   * @return Whether the invoiceNo field is set.
   */
  boolean hasInvoiceNo();
  /**
   * <code>optional string invoice_no = 1;</code>
   * @return The invoiceNo.
   */
  java.lang.String getInvoiceNo();
  /**
   * <code>optional string invoice_no = 1;</code>
   * @return The bytes for invoiceNo.
   */
  com.google.protobuf.ByteString
      getInvoiceNoBytes();

  /**
   * <code>optional string datetime = 2;</code>
   * @return Whether the datetime field is set.
   */
  boolean hasDatetime();
  /**
   * <code>optional string datetime = 2;</code>
   * @return The datetime.
   */
  java.lang.String getDatetime();
  /**
   * <code>optional string datetime = 2;</code>
   * @return The bytes for datetime.
   */
  com.google.protobuf.ByteString
      getDatetimeBytes();

  /**
   * <code>optional string email = 3;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional int32 total_value = 4;</code>
   * @return Whether the totalValue field is set.
   */
  boolean hasTotalValue();
  /**
   * <code>optional int32 total_value = 4;</code>
   * @return The totalValue.
   */
  int getTotalValue();

  /**
   * <code>optional int32 discounted_value = 5;</code>
   * @return Whether the discountedValue field is set.
   */
  boolean hasDiscountedValue();
  /**
   * <code>optional int32 discounted_value = 5;</code>
   * @return The discountedValue.
   */
  int getDiscountedValue();

  /**
   * <code>repeated .InvoiceItem items = 6;</code>
   */
  java.util.List<org.example.protos.InvoiceItem> 
      getItemsList();
  /**
   * <code>repeated .InvoiceItem items = 6;</code>
   */
  org.example.protos.InvoiceItem getItems(int index);
  /**
   * <code>repeated .InvoiceItem items = 6;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .InvoiceItem items = 6;</code>
   */
  java.util.List<? extends org.example.protos.InvoiceItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .InvoiceItem items = 6;</code>
   */
  org.example.protos.InvoiceItemOrBuilder getItemsOrBuilder(
      int index);
}
