// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invoices.proto

package org.example.protos;

public interface InvoicesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Invoices)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Invoice invoices = 1;</code>
   */
  java.util.List<org.example.protos.Invoice> 
      getInvoicesList();
  /**
   * <code>repeated .Invoice invoices = 1;</code>
   */
  org.example.protos.Invoice getInvoices(int index);
  /**
   * <code>repeated .Invoice invoices = 1;</code>
   */
  int getInvoicesCount();
  /**
   * <code>repeated .Invoice invoices = 1;</code>
   */
  java.util.List<? extends org.example.protos.InvoiceOrBuilder> 
      getInvoicesOrBuilderList();
  /**
   * <code>repeated .Invoice invoices = 1;</code>
   */
  org.example.protos.InvoiceOrBuilder getInvoicesOrBuilder(
      int index);
}
