// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invoices.proto

package org.example.protos;

/**
 * Protobuf type {@code Invoice}
 */
public final class Invoice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Invoice)
    InvoiceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Invoice.newBuilder() to construct.
  private Invoice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Invoice() {
    invoiceNo_ = "";
    datetime_ = "";
    email_ = "";
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Invoice();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.protos.InvoicesProtos.internal_static_Invoice_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.protos.InvoicesProtos.internal_static_Invoice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.protos.Invoice.class, org.example.protos.Invoice.Builder.class);
  }

  private int bitField0_;
  public static final int INVOICE_NO_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object invoiceNo_ = "";
  /**
   * <code>optional string invoice_no = 1;</code>
   * @return Whether the invoiceNo field is set.
   */
  @java.lang.Override
  public boolean hasInvoiceNo() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string invoice_no = 1;</code>
   * @return The invoiceNo.
   */
  @java.lang.Override
  public java.lang.String getInvoiceNo() {
    java.lang.Object ref = invoiceNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        invoiceNo_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string invoice_no = 1;</code>
   * @return The bytes for invoiceNo.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInvoiceNoBytes() {
    java.lang.Object ref = invoiceNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      invoiceNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATETIME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object datetime_ = "";
  /**
   * <code>optional string datetime = 2;</code>
   * @return Whether the datetime field is set.
   */
  @java.lang.Override
  public boolean hasDatetime() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string datetime = 2;</code>
   * @return The datetime.
   */
  @java.lang.Override
  public java.lang.String getDatetime() {
    java.lang.Object ref = datetime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        datetime_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string datetime = 2;</code>
   * @return The bytes for datetime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDatetimeBytes() {
    java.lang.Object ref = datetime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      datetime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CUSTOMER_ID_FIELD_NUMBER = 3;
  private int customerId_ = 0;
  /**
   * <code>optional int32 customer_id = 3;</code>
   * @return Whether the customerId field is set.
   */
  @java.lang.Override
  public boolean hasCustomerId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional int32 customer_id = 3;</code>
   * @return The customerId.
   */
  @java.lang.Override
  public int getCustomerId() {
    return customerId_;
  }

  public static final int EMAIL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object email_ = "";
  /**
   * <code>optional string email = 4;</code>
   * @return Whether the email field is set.
   */
  @java.lang.Override
  public boolean hasEmail() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string email = 4;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        email_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string email = 4;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_VALUE_FIELD_NUMBER = 5;
  private int totalValue_ = 0;
  /**
   * <code>optional int32 total_value = 5;</code>
   * @return Whether the totalValue field is set.
   */
  @java.lang.Override
  public boolean hasTotalValue() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 total_value = 5;</code>
   * @return The totalValue.
   */
  @java.lang.Override
  public int getTotalValue() {
    return totalValue_;
  }

  public static final int DISCOUNTED_VALUE_FIELD_NUMBER = 6;
  private int discountedValue_ = 0;
  /**
   * <code>optional int32 discounted_value = 6;</code>
   * @return Whether the discountedValue field is set.
   */
  @java.lang.Override
  public boolean hasDiscountedValue() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional int32 discounted_value = 6;</code>
   * @return The discountedValue.
   */
  @java.lang.Override
  public int getDiscountedValue() {
    return discountedValue_;
  }

  public static final int ITEMS_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private java.util.List<org.example.protos.InvoiceItem> items_;
  /**
   * <code>repeated .InvoiceItem items = 7;</code>
   */
  @java.lang.Override
  public java.util.List<org.example.protos.InvoiceItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .InvoiceItem items = 7;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.example.protos.InvoiceItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .InvoiceItem items = 7;</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .InvoiceItem items = 7;</code>
   */
  @java.lang.Override
  public org.example.protos.InvoiceItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .InvoiceItem items = 7;</code>
   */
  @java.lang.Override
  public org.example.protos.InvoiceItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, invoiceNo_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, datetime_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeInt32(3, customerId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, email_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, totalValue_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeInt32(6, discountedValue_);
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(7, items_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, invoiceNo_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, datetime_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, customerId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, email_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, totalValue_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, discountedValue_);
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, items_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.protos.Invoice)) {
      return super.equals(obj);
    }
    org.example.protos.Invoice other = (org.example.protos.Invoice) obj;

    if (hasInvoiceNo() != other.hasInvoiceNo()) return false;
    if (hasInvoiceNo()) {
      if (!getInvoiceNo()
          .equals(other.getInvoiceNo())) return false;
    }
    if (hasDatetime() != other.hasDatetime()) return false;
    if (hasDatetime()) {
      if (!getDatetime()
          .equals(other.getDatetime())) return false;
    }
    if (hasCustomerId() != other.hasCustomerId()) return false;
    if (hasCustomerId()) {
      if (getCustomerId()
          != other.getCustomerId()) return false;
    }
    if (hasEmail() != other.hasEmail()) return false;
    if (hasEmail()) {
      if (!getEmail()
          .equals(other.getEmail())) return false;
    }
    if (hasTotalValue() != other.hasTotalValue()) return false;
    if (hasTotalValue()) {
      if (getTotalValue()
          != other.getTotalValue()) return false;
    }
    if (hasDiscountedValue() != other.hasDiscountedValue()) return false;
    if (hasDiscountedValue()) {
      if (getDiscountedValue()
          != other.getDiscountedValue()) return false;
    }
    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInvoiceNo()) {
      hash = (37 * hash) + INVOICE_NO_FIELD_NUMBER;
      hash = (53 * hash) + getInvoiceNo().hashCode();
    }
    if (hasDatetime()) {
      hash = (37 * hash) + DATETIME_FIELD_NUMBER;
      hash = (53 * hash) + getDatetime().hashCode();
    }
    if (hasCustomerId()) {
      hash = (37 * hash) + CUSTOMER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCustomerId();
    }
    if (hasEmail()) {
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
    }
    if (hasTotalValue()) {
      hash = (37 * hash) + TOTAL_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalValue();
    }
    if (hasDiscountedValue()) {
      hash = (37 * hash) + DISCOUNTED_VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getDiscountedValue();
    }
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.protos.Invoice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protos.Invoice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protos.Invoice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protos.Invoice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protos.Invoice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protos.Invoice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protos.Invoice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protos.Invoice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.protos.Invoice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.protos.Invoice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.protos.Invoice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protos.Invoice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.protos.Invoice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Invoice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Invoice)
      org.example.protos.InvoiceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.protos.InvoicesProtos.internal_static_Invoice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.protos.InvoicesProtos.internal_static_Invoice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.protos.Invoice.class, org.example.protos.Invoice.Builder.class);
    }

    // Construct using org.example.protos.Invoice.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      invoiceNo_ = "";
      datetime_ = "";
      customerId_ = 0;
      email_ = "";
      totalValue_ = 0;
      discountedValue_ = 0;
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
      } else {
        items_ = null;
        itemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000040);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.protos.InvoicesProtos.internal_static_Invoice_descriptor;
    }

    @java.lang.Override
    public org.example.protos.Invoice getDefaultInstanceForType() {
      return org.example.protos.Invoice.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.protos.Invoice build() {
      org.example.protos.Invoice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.protos.Invoice buildPartial() {
      org.example.protos.Invoice result = new org.example.protos.Invoice(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.example.protos.Invoice result) {
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
    }

    private void buildPartial0(org.example.protos.Invoice result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.invoiceNo_ = invoiceNo_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.datetime_ = datetime_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.customerId_ = customerId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.email_ = email_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.totalValue_ = totalValue_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.discountedValue_ = discountedValue_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.protos.Invoice) {
        return mergeFrom((org.example.protos.Invoice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.protos.Invoice other) {
      if (other == org.example.protos.Invoice.getDefaultInstance()) return this;
      if (other.hasInvoiceNo()) {
        invoiceNo_ = other.invoiceNo_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasDatetime()) {
        datetime_ = other.datetime_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasCustomerId()) {
        setCustomerId(other.getCustomerId());
      }
      if (other.hasEmail()) {
        email_ = other.email_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasTotalValue()) {
        setTotalValue(other.getTotalValue());
      }
      if (other.hasDiscountedValue()) {
        setDiscountedValue(other.getDiscountedValue());
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000040);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              invoiceNo_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              datetime_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              customerId_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              email_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              totalValue_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              discountedValue_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 58: {
              org.example.protos.InvoiceItem m =
                  input.readMessage(
                      org.example.protos.InvoiceItem.PARSER,
                      extensionRegistry);
              if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(m);
              } else {
                itemsBuilder_.addMessage(m);
              }
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object invoiceNo_ = "";
    /**
     * <code>optional string invoice_no = 1;</code>
     * @return Whether the invoiceNo field is set.
     */
    public boolean hasInvoiceNo() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string invoice_no = 1;</code>
     * @return The invoiceNo.
     */
    public java.lang.String getInvoiceNo() {
      java.lang.Object ref = invoiceNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          invoiceNo_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string invoice_no = 1;</code>
     * @return The bytes for invoiceNo.
     */
    public com.google.protobuf.ByteString
        getInvoiceNoBytes() {
      java.lang.Object ref = invoiceNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        invoiceNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string invoice_no = 1;</code>
     * @param value The invoiceNo to set.
     * @return This builder for chaining.
     */
    public Builder setInvoiceNo(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      invoiceNo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string invoice_no = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearInvoiceNo() {
      invoiceNo_ = getDefaultInstance().getInvoiceNo();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string invoice_no = 1;</code>
     * @param value The bytes for invoiceNo to set.
     * @return This builder for chaining.
     */
    public Builder setInvoiceNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      invoiceNo_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object datetime_ = "";
    /**
     * <code>optional string datetime = 2;</code>
     * @return Whether the datetime field is set.
     */
    public boolean hasDatetime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string datetime = 2;</code>
     * @return The datetime.
     */
    public java.lang.String getDatetime() {
      java.lang.Object ref = datetime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          datetime_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string datetime = 2;</code>
     * @return The bytes for datetime.
     */
    public com.google.protobuf.ByteString
        getDatetimeBytes() {
      java.lang.Object ref = datetime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        datetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string datetime = 2;</code>
     * @param value The datetime to set.
     * @return This builder for chaining.
     */
    public Builder setDatetime(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      datetime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string datetime = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDatetime() {
      datetime_ = getDefaultInstance().getDatetime();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string datetime = 2;</code>
     * @param value The bytes for datetime to set.
     * @return This builder for chaining.
     */
    public Builder setDatetimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      datetime_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private int customerId_ ;
    /**
     * <code>optional int32 customer_id = 3;</code>
     * @return Whether the customerId field is set.
     */
    @java.lang.Override
    public boolean hasCustomerId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 customer_id = 3;</code>
     * @return The customerId.
     */
    @java.lang.Override
    public int getCustomerId() {
      return customerId_;
    }
    /**
     * <code>optional int32 customer_id = 3;</code>
     * @param value The customerId to set.
     * @return This builder for chaining.
     */
    public Builder setCustomerId(int value) {

      customerId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 customer_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCustomerId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      customerId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>optional string email = 4;</code>
     * @return Whether the email field is set.
     */
    public boolean hasEmail() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string email = 4;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          email_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string email = 4;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string email = 4;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      email_ = getDefaultInstance().getEmail();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 4;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      email_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private int totalValue_ ;
    /**
     * <code>optional int32 total_value = 5;</code>
     * @return Whether the totalValue field is set.
     */
    @java.lang.Override
    public boolean hasTotalValue() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 total_value = 5;</code>
     * @return The totalValue.
     */
    @java.lang.Override
    public int getTotalValue() {
      return totalValue_;
    }
    /**
     * <code>optional int32 total_value = 5;</code>
     * @param value The totalValue to set.
     * @return This builder for chaining.
     */
    public Builder setTotalValue(int value) {

      totalValue_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 total_value = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalValue() {
      bitField0_ = (bitField0_ & ~0x00000010);
      totalValue_ = 0;
      onChanged();
      return this;
    }

    private int discountedValue_ ;
    /**
     * <code>optional int32 discounted_value = 6;</code>
     * @return Whether the discountedValue field is set.
     */
    @java.lang.Override
    public boolean hasDiscountedValue() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional int32 discounted_value = 6;</code>
     * @return The discountedValue.
     */
    @java.lang.Override
    public int getDiscountedValue() {
      return discountedValue_;
    }
    /**
     * <code>optional int32 discounted_value = 6;</code>
     * @param value The discountedValue to set.
     * @return This builder for chaining.
     */
    public Builder setDiscountedValue(int value) {

      discountedValue_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 discounted_value = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearDiscountedValue() {
      bitField0_ = (bitField0_ & ~0x00000020);
      discountedValue_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<org.example.protos.InvoiceItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000040) != 0)) {
        items_ = new java.util.ArrayList<org.example.protos.InvoiceItem>(items_);
        bitField0_ |= 0x00000040;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.protos.InvoiceItem, org.example.protos.InvoiceItem.Builder, org.example.protos.InvoiceItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public java.util.List<org.example.protos.InvoiceItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public org.example.protos.InvoiceItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public Builder setItems(
        int index, org.example.protos.InvoiceItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public Builder setItems(
        int index, org.example.protos.InvoiceItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public Builder addItems(org.example.protos.InvoiceItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public Builder addItems(
        int index, org.example.protos.InvoiceItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public Builder addItems(
        org.example.protos.InvoiceItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public Builder addItems(
        int index, org.example.protos.InvoiceItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends org.example.protos.InvoiceItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public org.example.protos.InvoiceItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public org.example.protos.InvoiceItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public java.util.List<? extends org.example.protos.InvoiceItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public org.example.protos.InvoiceItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          org.example.protos.InvoiceItem.getDefaultInstance());
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public org.example.protos.InvoiceItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, org.example.protos.InvoiceItem.getDefaultInstance());
    }
    /**
     * <code>repeated .InvoiceItem items = 7;</code>
     */
    public java.util.List<org.example.protos.InvoiceItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.example.protos.InvoiceItem, org.example.protos.InvoiceItem.Builder, org.example.protos.InvoiceItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.example.protos.InvoiceItem, org.example.protos.InvoiceItem.Builder, org.example.protos.InvoiceItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000040) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Invoice)
  }

  // @@protoc_insertion_point(class_scope:Invoice)
  private static final org.example.protos.Invoice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.protos.Invoice();
  }

  public static org.example.protos.Invoice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<Invoice>
      PARSER = new com.google.protobuf.AbstractParser<Invoice>() {
    @java.lang.Override
    public Invoice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Invoice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Invoice> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.protos.Invoice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

